version: '3.8'

services:
  db:
    image: postgres:15
    container_name: simapro_db
    environment:
      POSTGRES_DB: simapro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D0d0lg4rut!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: simapro_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: D0d0lg4rut!
      DB_NAME: simapro_db
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
